# Generated by Django 5.2.1 on 2025-05-29 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idcategories', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('idclients', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Name')),
                ('lastname', models.CharField(blank=True, max_length=45, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=45, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('idorders', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                ('state', models.CharField(blank=True, default='pending', max_length=45, null=True, verbose_name='State')),
                ('idclients', models.ForeignKey(blank=True, db_column='idclients', null=True, on_delete=django.db.models.deletion.PROTECT, to='ferreteria.clients', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idproducts', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/', verbose_name='Image')),
                ('idcategories', models.ForeignKey(blank=True, db_column='idcategories', null=True, on_delete=django.db.models.deletion.PROTECT, to='ferreteria.categories', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('idorder_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('idorders', models.ForeignKey(blank=True, db_column='idorders', null=True, on_delete=django.db.models.deletion.CASCADE, to='ferreteria.orders', verbose_name='Order')),
                ('idproducts', models.ForeignKey(blank=True, db_column='idproducts', null=True, on_delete=django.db.models.deletion.PROTECT, to='ferreteria.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idcart', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date')),
                ('idclient', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.CASCADE, to='ferreteria.clients', verbose_name='Client')),
                ('idproduct', models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.CASCADE, to='ferreteria.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('idclient', 'idproduct')},
            },
        ),
    ]
